# Utilizza un'immagine Node.js ufficiale come immagine di base
FROM node:16-alpine as development

# Imposta la directory di lavoro nel container
WORKDIR /usr/src/app

# Copia i file di definizione delle dipendenze
COPY package*.json ./

# Installa le dipendenze
RUN npm install

# Copia il resto del codice sorgente dell'applicazione nella directory di lavoro del container
COPY . .

# Run Prisma generate Prisma Client
RUN npx prisma generate

# Espone la porta 3000
EXPOSE 3000

# Avvia l'applicazione in modalità sviluppo
CMD ["npm", "run", "start:dev"]
