# Utilizza un'immagine Node.js ufficiale come immagine di base
FROM node:16-alpine as development

# Imposta la directory di lavoro nel container
WORKDIR /usr/src/app

# Copia i file di definizione delle dipendenze
COPY package*.json ./

# Installa le dipendenze
RUN apk add --no-cache make gcc g++ python3 && \
    npm install && \
    apk del make gcc g++ python3

# Copia il resto del codice sorgente dell'applicazione nella directory di lavoro del container
COPY . .

# Copy the start script into the container
COPY start.sh ./

# Make the start script executable
RUN chmod +x start.sh

# Espone la porta 3000
EXPOSE 3000

# Avvia l'applicazione in modalità sviluppo
CMD ["./start.sh"]
